for(i in 2:521){
	tmp <- get.edgelist(g15[[i]], names=F)
	tmp <- cbind(tmp, rep(1,nrow(tmp)))
	write.table(tmp, "./tmp.txt", quote=F, sep=" ", row.names=F, col.names=F)
	cmd = paste0("./gtrieScanner -s 4 -m gtrie undir4.gt -g tmp.txt -o RESULTS/15/15_4_", i, ".txt")
  	system(cmd)
  	tmp <- get.edgelist(g30[[i]], names=F)
	tmp <- cbind(tmp, rep(1,nrow(tmp)))
	write.table(tmp, "./tmp.txt", quote=F, sep=" ", row.names=F, col.names=F)
	cmd = paste0("./gtrieScanner -s 4 -m gtrie undir4.gt -g tmp.txt -o RESULTS/30/30_4_", i, ".txt")
  	system(cmd)
  	tmp <- get.edgelist(g45[[i]], names=F)
	tmp <- cbind(tmp, rep(1,nrow(tmp)))
	write.table(tmp, "./tmp.txt", quote=F, sep=" ", row.names=F, col.names=F)
	cmd = paste0("./gtrieScanner -s 4 -m gtrie undir4.gt -g tmp.txt -o RESULTS/45/45_4_", i, ".txt")
  	system(cmd)
  	tmp <- get.edgelist(g60[[i]], names=F)
	tmp <- cbind(tmp, rep(1,nrow(tmp)))
	write.table(tmp, "./tmp.txt", quote=F, sep=" ", row.names=F, col.names=F)
	cmd = paste0("./gtrieScanner -s 4 -m gtrie undir4.gt -g tmp.txt -o RESULTS/60/60_4_", i, ".txt")
  	system(cmd)
  	tmp <- get.edgelist(g75[[i]], names=F)
	tmp <- cbind(tmp, rep(1,nrow(tmp)))
	write.table(tmp, "./tmp.txt", quote=F, sep=" ", row.names=F, col.names=F)
	cmd = paste0("./gtrieScanner -s 4 -m gtrie undir4.gt -g tmp.txt -o RESULTS/75/75_4_", i, ".txt")
  	system(cmd)
  	tmp <- get.edgelist(g90[[i]], names=F)
	tmp <- cbind(tmp, rep(1,nrow(tmp)))
	write.table(tmp, "./tmp.txt", quote=F, sep=" ", row.names=F, col.names=F)
	cmd = paste0("./gtrieScanner -s 4 -m gtrie undir4.gt -g tmp.txt -o RESULTS/90/90_4_", i, ".txt")
  	system(cmd)
}